### ISSUE TITLE
Evaluate @Beamanator for the ContributorPlus role

### ISSUE THREAD

**Issue by Beamanator** [Beamanator/Just-To-Learn#142]
👋 Hey, you're the chosen one to champion evaluating this contributor to address their suitability for the [Contributor Plus](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) role. Could this be our latest rising ⭐ ?!

____

1. Obtain the list of closed assigned issues by following this Github search [link](https://github.com/Expensify/App/issues?q=is%3Aissue+assignee%3ABeamanator+sort%3Aupdated-desc+is%3Aclosed+)
2. Obtain the list of closed issues reported by following this Github search [link](https://github.com/Expensify/App/issues?q=is%3Aissue+%22reported+by+%40Beamanator%22+is%3Aclosed+sort%3Aupdated-desc)
3. Cross-reference the contributor's GH handle on the [Do Not Hire (DNH) spreadsheet](https://docs.google.com/spreadsheets/d/1xEQeqFwBzirc-AGC4tYgNNLO7cBS50gSKWXv3e2U6Y4/edit#gid=0). If they're on it, grab the notes to include for discussion. 
4. In the #contributor-plus channel, you'll find the thread auto-created to discuss this contributor. Use that to post your findings, and tag a few people that have worked with the contributor recently for additional opinions.

Example structure

```
[Closed assigned issues](link): 10
[Closed issued reported](link): 5
Do not hire check: [Pass/Fail]
- notes
- notes

CC: <@list of people that have worked on issues/PRs with the contributor recently>
```

_Check out the [SO for a few ideas](https://stackoverflow.com/c/expensify/questions/14789) of what to look out for in the gathered data. Feel free to add to it as well!_ 
____

### Task list
- [ ] Post the gathered data in the Slack thread
- [ ] Wrap-up the thread with the proposed next steps (Send an offer / pass)
- [ ] [If applicable] Send the contributor a DM in Slack to present the offer. Here's an example message if you need one: 

```
Hey xx! 

Thank you for being a valuable member of the Expensify Open Source community. We've been impressed with your contributions so far, and wanted to offer you the opportunity to join the ContributorPlus (C+) team. 

It's a great opportunity to earn more by supporting other members of the community with proposal and PR reviews, in addition to reporting any bugs you find or fix yourself. 

Can you [take a read at the overview of the role](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) and let me know if you're interested? Happy to answer any questions you may have in the meantime! 
```
- [ ] [If applicable] If the contributor accepts the offer, follow the [onboarding steps](https://stackoverflow.com/c/expensify/questions/11623) to get them added to the team officially.

______

Once you've completed all the applicable items in the checklist, post/link to a recap summary of the decision in this issue and close it. You're done! 🚀 

Triggered auto assignment to @Christinadobrzyn
